### ISSUE TITLE
uvprov - Setup refresh interval as env variable

### ISSUE THREAD

**Issue by jkesanie** [ATTX-project/uv-provenance-service#1]
#### Desc

Right now the refresh interval is hard-coded. 
Add variable that can be used to change that value (in minutes)
#### DoD
New variable in action

**Comment by blankdots** [comment]
`QTIME` environment variable set up and added to documentation: https://github.com/ATTX-project/ATTX-project.github.io/blob/dev/attx_project/Service-UVProvenance.md
